package com.motoyav2.cobranza.domain.enums;

public enum TipoEventoCobranza {
    CONTACTO_EXITOSO,
    CONTACTO_FALLIDO,
    MENSAJE_WHATSAPP,
    PROMESA_REGISTRADA,
    PROMESA_CUMPLIDA,
    PROMESA_INCUMPLIDA,
    PROMESA_CANCELADA,
    VOUCHER_RECIBIDO,
    VOUCHER_APROBADO,
    VOUCHER_RECHAZADO,
    PAGO_APLICADO,
    COMPROBANTE_GENERADO,
    ESTRATEGIA_DISPARADA,
    ESTRATEGIA_ENTREGADA,
    ESTRATEGIA_FALLIDA,
    CASO_ASIGNADO,
    ESTADO_CAMBIADO,
    NIVEL_ESCALADO,
    EXCEPCION_REGISTRADA,
    CASO_CERRADO,
    ACUERDO_REGISTRADO,
    ACUERDO_INCUMPLIDO,
    ACUERDO_CUMPLIDO
}