package com.motoyav2.cobranza.domain.enums;

public enum TipoAlerta {
    PROMESA_VENCE_HOY,
    PROMESA_VENCE_MANANA,
    PROMESA_INCUMPLIDA,
    CASO_SIN_GESTION,
    ESCALACION_REQUERIDA,
    CASO_CRITICO_SIN_AGENTE,
    VOUCHER_PENDIENTE,
    VOUCHER_MONTO_DISCREPANTE,
    ESTRATEGIA_FALLIDA_MULTIPLE,
    SLA_VENCE_HOY,
    SLA_VENCIDO,
    PAGO_NO_CONCILIADO
}
