package com.motoyav2.evaluacion.domain.enums;

public enum EtapaDeEvaluacion {
  RECEPCION,
  REVISION_DOCUMENTAL_TITULAR,
  REVISION_DOCUMENTAL_FIADOR,
  ENTREVISTA_TITULAR,
  ENTREVISTA_FIADOR,
  COMPROBACION_REFERENCIAS,
  EVALUACION_REFERENCIAS,
  EVALUACION_FINANCIERA,
  EVALUACION_DEL_VEHICULO,
  DECISION_FINAL,
  NOTIFICACION_POR_CORREO
}
