package com.motoyav2.evaluacion.domain.enums;

public enum TipoDeDocumento {
  DNI_FRENTE,
  DNI_REVERSO,
  LICENCIA_CONDUCIR_FRENTE,
  LICENCIA_CONDUCIR_REVERSO,
  RECIBO_DE_SERVICIO,
  COMPROBANTE_DE_INGRESOS,
  BOLETA_DE_PAGO,
  COMPROBANTE_DOMICILIO,
  FACHADA_DOMICILIO,
  CERTIFICADO_DE_TRABAJO,
  FOTOGRAFIA_DOMICILIO,
  FOTOGRAFIA_CLIENTE,
  CARNET_DE_EXTRANJERIA,
  PASAPORTE,
  OTROS
}
